version: '3'

services:
  #
  # Applications
  teamengine:
    build: ./teamengine
    container_name: teamengine@${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    expose: 
      - "8081"
    environment: 
      - VIRTUAL_HOST=teamengine.elasticlabs.co
      - VIRTUAL_PORT=8081
      - TE_BASE=${TE_INSTALLDIR}
      - TE_VERSION=${TE_VERSION}
    volumes:
      - te-base:${TE_INSTALLDIR}
      - te-java-scripts:${TE_INSTALLDIR}/resources/lib
      - te-ctl-scripts:${TE_INSTALLDIR}/scripts
    #  - ./ets-data:/root/ets-data
    networks:
      - apps

volumes:
  te-base:
  te-java-scripts:
  te-ctl-scripts:

networks:
  apps: