version: '3'

services:
  #
  # Applications
  te-proxy:
    image: ${COMPOSE_PROJECT_NAME}_te-proxy:latest
    container_name: te-proxy4${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    expose:
      - "80"
    build:
      context: ./proxy
    environment:
      - DHPARAM_GENERATION=false
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=${TE_VHOST}
      - LETSENCRYPT_HOST=${TE_VHOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - https-revproxy
      - teamengine
  
  teamengine:
    build:
      context: ./teamengine
      dockerfile: Dockerfile
      args:
        - TE_WEBAPP=${TE_WEBAPP}
        - TE_VERSION=${TE_VERSION}
        - GIT_NAME="Elastic Labs"
        - GIT_MAIL="contact@elasticlabs.co"
    container_name: teamengine4${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    expose: 
      - "8080"
    environment: 
      - DHPARAM_GENERATION=false
    volumes:
      - te-webapp:${TE_WEBAPP}
    networks:
      - teamengine

volumes:
  te-webapp:

networks:
  https-revproxy:
    external:
      name: ${APPS_NETWORK}
  teamengine: