version: '3'

services:
  #
  # Applications
  teamengine:
    build:
      context: ./teamengine
      dockerfile: Dockerfile
      args:
        - TE_WEBAPP=${TE_WEBAPP}
        - TE_VERSION=${TE_VERSION}
        - GIT_NAME="Elastic Labs"
        - GIT_MAIL="contact@elasticlabs.co"
    container_name: teamengine4${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    expose: 
      - "8080"
    environment: 
      - VIRTUAL_HOST=teamengine.elasticlabs.co
      - VIRTUAL_PORT=8080
    volumes:
      - te-webapp:${TE_WEBAPP}
    networks:
      - apps

volumes:
  te-base:
  te-data:
  te-webapp:

networks:
  apps: