version: '3'

services:
  #
  # Applications
  teamengine:
    build:
      context: ./teamengine
      dockerfile: Dockerfile
      args:
        - TE_WEBAPP=${TE_WEBAPP}
        - TE_BASEDIR=${TE_BASEDIR}
        - TE_VERSION=${TE_VERSION}
        - GIT_NAME="Elastic Labs"
        - GIT_MAIL="contact@elasticlabs.co"
    container_name: teamengine@${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    expose: 
      - "8081"
    environment: 
      - VIRTUAL_HOST=teamengine.elasticlabs.co
      - VIRTUAL_PORT=8081
    volumes:
      - te-base:${TE_WEBAPP}
      - te-java-scripts:${TE_WEBAPP}/resources/lib
      - te-ctl-scripts:${TE_WEBAPP}/scripts
      ./ets-data:${TE_BASEDIR}
    networks:
      - apps

volumes:
  te-base:
  te-java-scripts:
  te-ctl-scripts:

networks:
  apps: