version: '3'

services:
#
# Applications


#  geonetwork:
#    build: ./geonetwork
#    container_name: geonetwork4${COMPOSE_PROJECT_NAME}
#    restart: unless-stopped
#    depends_on: 
#      - es01
#      - kibana
#    expose: 
#      - "8080"
#    environment:
#      - VIRTUAL_HOST=geonetwork.sdi.elasticlabs.co
#      - VIRTUAL_PORT=8080
#    env_file:
#      - ./geonetwork/.env
#    volumes:
#      - geonetwork-base:/usr/local/geonetwork
#      - geonetwork-data:/var/local/geonetwork
#    networks:
#      - apps

#volumes:
#  mbtiles-data:

networks:
  apps: